version: '2'

services:

  web:
    container_name: web
    build:
      context: .
    ports:
      - "80:9080"
      - "443:9443"
    logging:
      driver: splunk
      options:
        splunk-url: https://127.0.0.1:8088
        splunk-token: 00000000-0000-0000-0000-000000000000
        tag: "logger-test"
        splunk-insecureskipverify: "true"
